---

- hosts: all
  become: true
  pre_tasks:


  - name: install update
    tags: all
    apt:
     upgrade: dist
     update_cache: yes


- hosts: web_server
  become: true
  tasks:


  - name: install apache package
    apt: 
     name:
      - apache2
      - libapache2-mod-php
     state: latest
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  
  - name: copy main to server
    copy: 
      src: main.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
  
- hosts: file_server
  become: true
  tasks: 


  - name: Install Samba
    tags: rulz
    apt:
     name: samba
     state: latest
    when: ansible_distribution == "Ubuntu"
